services:
    app:
        build:
            context: .
        image: fastapi-core/python:3.12
        container_name: fastapi-core-app
        env_file: ".env"
        environment:
            - PYDEVD_DISABLE_FILE_VALIDATION=1
        restart: unless-stopped
        command: poetry run python -m debugpy --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - "8000:8000"
            - "5678:5678"
        volumes:
            - ./src:/code/src
        networks:
            - fastapi-core
networks:
    fastapi-core:
        driver: bridge
